---
#  ________  ________  _____ ______   ________  ________  _________  _________  ________  ________     
# |\   ____\|\   __  \|\   _ \  _   \|\   __  \|\   __  \|\___   ___\\___   ___\\   __  \|\   ____\    
# \ \  \___|\ \  \|\  \ \  \\\__\ \  \ \  \|\ /\ \  \|\  \|___ \  \_\|___ \  \_\ \  \|\  \ \  \___|    
# \ \  \    \ \  \\\  \ \  \\|__| \  \ \   __  \ \   __  \   \ \  \     \ \  \ \ \   __  \ \  \  ___  
#   \ \  \____\ \  \\\  \ \  \    \ \  \ \  \|\  \ \  \ \  \   \ \  \     \ \  \ \ \  \ \  \ \  \|\  \ 
#    \ \_______\ \_______\ \__\    \ \__\ \_______\ \__\ \__\   \ \__\     \ \__\ \ \__\ \__\ \_______\
#     \|_______|\|_______|\|__|     \|__|\|_______|\|__|\|__|    \|__|      \|__|  \|__|\|__|\|_______| 


# Spawn Area
spawn:
  position1: 0:60:0:spawn
  position2: 10:60:0:spawn

# Time in Seconds of how long the CombatTag will be
tag-time: 30
...